### ISSUE TITLE
JSON Format in messages

### ISSUE THREAD

**Issue by Lyrians** [axelrindle/Broadcaster-Plugin#20]
Let me explain briefly,

I have a survival server, which has 4 worlds:
- Survival
- Nether
- Means
- End

Nether, Resources, and End are worlds that restart every 7 days. These worlds, it has a hologram in the lobby, and every reboot I have to move it to the new lobby, when using / hd movehere <hologram>, the server breaks, a lot of errors start jumping, and after that ... it goes off.
When I turn it on again, and use the same command, it works perfectly.

By the way, a suggestion: It would be nice if the plugin supports JSON format for announcements.

**Comment by axelrindle** [comment]
Doesn't seem to be related to this plugin. An error with `HolographicDisplays` instead?

Also, without any kind of exception stacktraces I'm not able to help.

---
```
By the way, a suggestion: It would be nice if the plugin supports JSON format for announcements.
```
Please elaborate.

**Comment by Lyrians** [comment]
Hahaha it's true, forgive me. It was that I was going to report errors, and everything got mixed up.
Forgive me, it was my mistake.

I wanted to make the suggestion here, since I didn't know where to do it.
With JSON Format / Text, I mean this:

`["", {"text": "Hello, i'am"}, {"text": "JSON", "clickEvent": {"action": "open_url", "value": "https: // github .com / axelrindle / Broadcaster-Plugin / issues / 20 "}}, {" text ":" text "}]`

https://minecraft.tools/en/json_text.php?json=Hello%2C%20i%26%2339%3Bam%20%3Ca%20data-openurl%3D%22https%3A%2F%2Fgithub.com%2Faxelrindle%2FBroadcaster-Plugin%2Fissues%2F20%22%20class%3D%22openurl%22%20href%3D%22https%3A%2F%2Fgithub.com%2Faxelrindle%2FBroadcaster-Plugin%2Fissues%2F20%22%3EJSON%20%3C%2Fa%3Etext%26nbsp%3B

**Comment by axelrindle** [comment]
Interesting feature. Will definitely put this on my TODO list.

Thanks for the suggestion :+1:
